services:
  - type: web
    name: line-expense-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python line_bot.py
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_CHANNEL_SECRET  
        sync: false
      - key: PORT
        value: 10000 